export const api_url='https://education.tablighshop.com/api';
export const apps_slug='profet';
export const apps_title='নবী রাসূলের জীবনী';
export const DAILY_BOXES=30;
export const video_coin_per_box=10;
export const story_detail_per_box=10;
export const daily_coin_count=10;
export const max_claim_per_day=60;
export const story_detail_points=100;